### ISSUE TITLE
Support for Apple Silicon Macs and the M1 Processor

### ISSUE THREAD

**Issue by petin** [StringCare/KotlinGradlePlugin#14]
I am not able to build my project any more on a macbook with M1 Processor.

`Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/fm/sf9z9g415x92gt94m1g12l2r0000gn/T/libsignKey.dylib183792219017920951: dlopen(/private/var/folders/fm/sf9z9g415x92gt94m1g12l2r0000gn/T/libsignKey.dylib183792219017920951, 0x0001): tried: '/private/var/folders/fm/sf9z9g415x92gt94m1g12l2r0000gn/T/libsignKey.dylib183792219017920951' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libsignKey.dylib183792219017920951' (no such file)
	at components.Stark$Companion.loadLib(Stark.kt:32)
	at components.Stark$Companion.access$loadLib(Stark.kt:10)
	at components.Stark.<clinit>(Stark.kt:14)
	at components.AParserKt.obfuscateFile(AParser.kt:40)
	at StringCare$apply$5$1.invoke(StringCare.kt:121)
	at StringCare$apply$5$1.invoke(StringCare.kt:6)
	at components.FingerprintKt.fingerPrint(Fingerprint.kt:85)
	at StringCare$apply$5.invoke(StringCare.kt:100)
	at StringCare$apply$5.invoke(StringCare.kt:6)
	at components.ExecutionListener.beforeExecute(ExecutionListener.kt:36)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
.
.
.`

**incompatible architecture (have 'x86_64', need 'arm64e')**

Any chance to add support? Thank you in advance

**Comment by efraespada** [comment]
It seems the library needs an update. 🤔 

Sadly I don't have an M1. I'm sure with time I'll fix it, but right now it is impossible.

**Comment by petin** [comment]
Any update on this? :)
